using UnityEngine;

namespace NBF
{
    public class FHook : FGearBase
    {
        public HookAsset hookAsset;

        private void Awake()
        {
            hookAsset = GetComponent<HookAsset>();
        }
        
        protected override void OnInit()
        {
            
            // transform.position = Rod.lineHandler.LineConnector_2.transform.position;
            // transform.rotation = Rod.lineHandler.LineConnector_2.transform.rotation; // 确保旋转也同步
            // SetParent(Rod.lineHandler.LineConnector_2.transform);
            
            
            SetParent(Rod.Line.Lure.transform);
            transform.localPosition = Vector3.zero;
            
            // var target = lineHandler.LineConnector_2.GetComponent<Rigidbody>();
            // var joint = Hook.gameObject.GetComponent<ConfigurableJoint>();
            // joint.connectedBody = target;
        }
    }
}