// using UnityEngine;
// using UnityEngine.Video;
//
// namespace NBF
// {
//     public class Init : MonoBehaviour
//     {
//
//         private void Awake()
//         {
//             Debug.Log($"assetsPath = {Application.streamingAssetsPath}  persistentDataPath={Application.persistentDataPath}");
//             DontDestroyOnLoad(gameObject);
//             Game.SetInitCallback(gameObject, StartGame);
//         }
//         
//
//         public void StartGame()
//         {
//             OpenUI();
//         }
//
//
//         private void OpenUI()
//         {
//             
//         }
//     }
// }