using System.Collections;
using Fantasy;
using UnityEngine;

namespace NBF
{
    public class FReel : FGearBase
    {
        public bool isBlockLineByFinger { get; set; }


        [SerializeField] public float reelingDrag = 1f;

        public ReelAsset Asset;
        public ReelAnimator AnimatorCtrl;

        private void Awake()
        {
            Asset = GetComponent<ReelAsset>();
            AnimatorCtrl = Asset.animator.gameObject.GetComponent<ReelAnimator>();
            if (AnimatorCtrl == null)
            {
                AnimatorCtrl = Asset.animator.gameObject.AddComponent<ReelAnimator>();
            }
        }

        protected override void OnInit()
        {
            
        }
    }
}