// using UnityEngine;
//
// public class HandsAnimEvents : MonoBehaviour
// {
// 	public FPlayer player;
//
// 	private void Start()
// 	{
// 	}
//
// 	private void Update()
// 	{
// 	}
//
// 	public void UnlockReel()
// 	{
// 		if ((bool)player)
// 		{
// 			player.currentRod.currentReel.LockUnlock();
// 			GetComponent<Animator>().SetBool("RHandReelUnlock", value: false);
// 			GetComponent<Animator>().SetBool("RHandReelLock", value: false);
// 		}
// 	}
//
// 	public void UnlockReelWithHandAnimation()
// 	{
// 		if ((bool)player)
// 		{
// 			player.UnlockLockReel();
// 		}
// 	}
//
// 	public void ResetThrow()
// 	{
// 		GetComponent<Animator>().SetBool("RHandThrowFar", value: false);
// 		GetComponent<Animator>().SetBool("RHandThrowNear", value: false);
// 	}
//
// 	public void BlockLineByFinger()
// 	{
// 		if ((bool)player && (bool)player.currentRod && player.fishingMode != 0)
// 		{
// 			player.currentRod.currentReel.isBlockLineByFinger = true;
// 		}
// 	}
//
// 	public void UnBlockLineByFinger()
// 	{
// 		if ((bool)player && player.fishingMode != 0 && (bool)player.currentRod)
// 		{
// 			if (player.currentRod.throwForcePower > 0f)
// 			{
// 				player.currentRod.ForceThrow();
// 			}
// 			player.currentRod.currentReel.isBlockLineByFinger = false;
// 		}
// 	}
//
// 	public void UnBlockLineByFingerNear()
// 	{
// 		if ((bool)player && player.fishingMode != 0 && (bool)player.currentRod)
// 		{
// 			if (player.currentRod.throwForcePower > 0f)
// 			{
// 				player.currentRod.ForceThrow(isNear: true);
// 			}
// 			player.currentRod.currentReel.isBlockLineByFinger = false;
// 			player.OutLineFromLeftHandHelper(player.currentRod.fishingLine.currentLineHandler.LineConnector_1.transform);
// 		}
// 	}
//
// 	public void PutHandOnReel()
// 	{
// 		if ((bool)player && player.currentRod.fishingLine.currentLineHandler.PhisicsLineOut > 0f && !player.currentRod.currentReel.isHandOnHandle)
// 		{
// 			player.InteractiveLeftHand(player.currentRod.currentReel.handle);
// 		}
// 	}
//
// 	public void CatchFish()
// 	{
// 		player.currentRod.CastFish();
// 	}
//
// 	public void DestroyCurrentFish()
// 	{
// 		player.currentRod.DestroyCurrentFish();
// 	}
//
// 	public void ShowFishPanel()
// 	{
// 		// FScriptsHandler.Instance.m_HudManager.ShowHideFishCatchPanel();
// 	}
//
// 	public void DestroyRod()
// 	{
// 		if ((bool)player && (bool)player.currentRod)
// 		{
// 			Destroy(player.currentRod.gameObject);
// 			player.currentRod = null;
// 		}
// 	}
// }
