using UnityEngine;
using UnityEngine.UI;

namespace NBF.Blur
{
    public class TestBlur : MonoBehaviour
    {
        public RawImage raw;

        public void Test()
        {
            Shader.SetGlobalInt("_UIBlurRefresh", 1);

            // var blur = URPRendererFeatureUtil.GetRendererFeature<UIBlurDualKawaseFeature>();
            // blur?.RefreshOnce();
        }


        void LateUpdate()
        {
            if (!raw) return;
            raw.texture = Shader.GetGlobalTexture("_UIBlurTexture");
        }
    }
}