using UnityEngine;

namespace NBF
{
    public class FLure : FGearBase
    {
        protected override void OnInit()
        {
            // transform.position = Rod.lineHandler.LineConnector_1.transform.position;
            
            // Lure.gameObject.GetComponent<ConfigurableJoint>().connectedBody =
            //     lineHandler.LineConnector_1.GetComponent<Rigidbody>();
            // LureHookWaterDisplacement = Lure.GetComponent<FWaterDisplacement>();
            
            // SetParent(Rod.lineHandler.LineConnector_1.transform);
            
            SetParent(Rod.Line.Lure.transform);
            transform.localPosition = Vector3.zero;
        }
    }
}